selenium 은 실제 웹페이지를 실행하기 때문에 
실행할  웹브라우저의 드라이버가 필요하다

마이크로소프트 엣지 드라이버 저장소: https://msedgewebdriverstorage.z22.web.core.windows.net/

구글 크롬 드라이버 저장소 : https://sites.google.com/a/chromium.org/chromedriver/downloads

In [ ]:
!conda install selenium -y
# !pip install selenium

# 인천 해양 수질 조사 정보 
https://icloud.incheon.go.kr/arcgis/apps/sites/#/opendatahub/datasets/86b9109edaf54c559f72795e6368eb2a/data?geometry=124.541%2C37.079%2C128.156%2C37.842&layer=0

In [ ]:
!conda env list

In [1]:
import selenium as sel
import time

In [2]:
print(sel.__version__)

3.141.0

# selenium import , URL 설정

In [3]:
from selenium import webdriver 

URL = 'https://icloud.incheon.go.kr/arcgis/apps/sites/#/opendatahub/datasets/86b9109edaf54c559f72795e6368eb2a/data?geometry=124.541%2C37.079%2C128.156%2C37.842&layer=0'

#  브라우저 종류 선택 및 드라이버 경로 설정

In [4]:
# options = Options() 
# options.binary_location= 'C:/Program Files/Google/Chrome/Application/chrome.exe' 
# driver = webdriver.Chrome('chromedriver.exe', chrome_options = options)

driver = webdriver.Chrome('chromedriver.exe')
# URL을 불러오는 시간이 있어 delay를 줘서 다음 작업이 잠시 후에 작동되도록 해야한다
time.sleep(0.5)

# URL 로드

In [5]:
driver.get(url=URL)
time.sleep(5)

# 값 불러오기

In [6]:
# find_all_tabel = driver.find_elements_by_xpath('//*[@id="not-map"]/div[@class="row"]/div[]')
find_all_tabel = driver.find_elements_by_css_selector('tbody > tr >td')
html = find_all_tabel[6].get_attribute('innerHTML')
print(html)
html = find_all_tabel[50].get_attribute('innerHTML')
print(html)

인천항 도크앞

영흥도 서방

In [7]:
for i, text in enumerate(find_all_tabel):
    print(text.text)
    if i > 10 : break

1
1
2019년 1분기
2019
1
1
인천항 도크앞
2019. 2. 13. 오후 6:24
0.6
8.08
12.2
30.02

# 테이블 헤더 파싱

In [8]:

tabel_header = driver.find_elements_by_css_selector('thead > tr > th > span > span:nth-child(2)  ')
header_html = tabel_header[0].get_attribute('innerHTML')
print(header_html)

objectid

# 테이블 헤더 정보 저장

In [9]:
dataframe_header = []
for one_tabel_header in tabel_header:
    header = one_tabel_header.text
    dataframe_header.append(header)
    
print(len(dataframe_header))
dataframe_header

44

['objectid',
 'OBJECTID',
 'loc_time',
 'loc_year',
 'loc_qtr',
 'loc_no',
 'loc_nm',
 'sample_day',
 'temp',
 'ph',
 'do_',
 'salinity',
 'cod',
 'coliform_cnt',
 't_n',
 't_p',
 'cn',
 'cu',
 'pb',
 'cd',
 'zn',
 'cr',
 'as_',
 'ni',
 'hg',
 'phenol',
 'no3_n',
 'no2_n',
 'nh3_n',
 'din',
 'dip',
 'chl_a',
 'low_do',
 'transparency',
 'toc',
 'din_wqi',
 'dip_wqi',
 'chl_a_wqi',
 'low_do_wqi',
 'transparency_wqi',
 'wqi_score',
 'wqi_grade',
 'gubun',
 'timeseries']

# 테이블 값 저장

In [10]:
dataframe_columns = []

row = []

for i, one_data in enumerate(find_all_tabel):
    if i % len(dataframe_header) == 0 and i !=0:
        dataframe_columns.append(row)
        row = []
    row.append(one_data.text)
    
    

print(len(row))
dataframe_columns[:5]

44

[['1',
  '1',
  '2019년 1분기',
  '2019',
  '1',
  '1',
  '인천항 도크앞',
  '2019. 2. 13. 오후 6:24',
  '0.6',
  '8.08',
  '12.2',
  '30.02',
  '2.24448',
  '54',
  '0.561',
  '0.045',
  '0',
  '0.00288561',
  '0.00091424',
  '0.00007514',
  '0.01116781',
  '',
  '0.00000773',
  '0.00153819',
  '0',
  '0',
  '0.1859',
  '0.0161',
  '0.19835505',
  '0.40035505',
  '0.0346',
  '3.48',
  '102.8',
  '1.5',
  '1.58',
  '1',
  '3',
  '5',
  '1',
  '1',
  '36',
  'Ⅲ',
  '인천해역',
  '201903'],
 ['2',
  '2',
  '2019년 1분기',
  '2019',
  '1',
  '34',
  '영흥도 서방',
  '2019. 2. 13. 오전 12:30',
  '2',
  '8.02',
  '11.43',
  '30.99',
  '2.72544',
  '1',
  '0.258',
  '0.038',
  '0',
  '0.00133017',
  '0.00011098',
  '0.00003369',
  '0.0098693',
  '',
  '0.0000136',
  '0.00081578',
  '0.00003',
  '0',
  '0.1684',
  '0.0108',
  '0.03960713',
  '0.21880713',
  '0.0348',
  '0',
  '102',
  '2',
  '1.24',
  '1',
  '3',
  '1',
  '1',
  '1',
  '24',
  'Ⅱ',
  '인천해역',
  '201903'],
 ['3',
  '3',
  '2019년 1분기',
  '2019',
  '1',
  '3',
  '인천남항 전면',
  '2019. 2. 13. 오후 6:11',
  '0.5',
  '8.12',
  '12.02',
  '30.3',
  '0.6012',
  '18',
  '0.462',
  '0.046',
  '0',
  '0.0020066',
  '0.00023836',
  '0.00004655',
  '0.00835613',
  '',
  '0.00000693',
  '0.00114348',
  '0',
  '0',
  '0.1607',
  '0.0044',
  '0.10587717',
  '0.27097717',
  '0.0309',
  '2.61',
  '102',
  '1.5',
  '1.63',
  '1',
  '2',
  '3',
  '1',
  '1',
  '28',
  'Ⅱ',
  '인천해역',
  '201903'],
 ['4',
  '4',
  '2019년 1분기',
  '2019',
  '1',
  '4',
  '오이도 북방',
  '2019. 2. 13. 오전 1:57',
  '1.8',
  '8.08',
  '12.19',
  '29.64',
  '2.96592',
  '170',
  '0.889',
  '0.073',
  '0',
  '0.00337544',
  '0.00051722',
  '0.00007143',
  '0.00978919',
  '',
  '0.0000116',
  '0.00386156',
  '0',
  '0',
  '0.2246',
  '0.0143',
  '0.59906321',
  '0.83796321',
  '0.0576',
  '0',
  '107.4',
  '1.2',
  '1.63',
  '5',
  '5',
  '1',
  '1',
  '1',
  '36',
  'Ⅲ',
  '인천해역',
  '201903'],
 ['5',
  '5',
  '2019년 1분기',
  '2019',
  '1',
  '5',
  '세어도 우측',
  '2019. 2. 13. 오후 7:26',
  '0.9',
  '8.05',
  '11.93',
  '29.56',
  '1.92384',
  '62',
  '0.681',
  '0.049',
  '0',
  '0.00308309',
  '0.00041171',
  '0.00007041',
  '0.00967324',
  '',
  '0.00000786',
  '0.00159155',
  '0',
  '0',
  '0.2654',
  '0.0095',
  '0.2878986',
  '0.5627986',
  '0.042',
  '1.375',
  '101.5',
  '1.1',
  '1.5',
  '4',
  '4',
  '1',
  '1',
  '1',
  '32',
  'Ⅱ',
  '인천해역',
  '201903']]

# dataframe 생성

In [11]:
import pandas as pd 
dataframe = pd.DataFrame(dataframe_columns, columns=dataframe_header)
dataframe

,objectid,OBJECTID,loc_time,loc_year,loc_qtr,loc_no,loc_nm,sample_day,temp,ph,...,toc,din_wqi,dip_wqi,chl_a_wqi,low_do_wqi,transparency_wqi,wqi_score,wqi_grade,gubun,timeseries
0,1,1,2019년 1분기,2019,1,1,인천항 도크앞,2019. 2. 13. 오후 6:24,0.6,8.08,...,1.58,1,3,5,1,1,36,Ⅲ,인천해역,201903
1,2,2,2019년 1분기,2019,1,34,영흥도 서방,2019. 2. 13. 오전 12:30,2,8.02,...,1.24,1,3,1,1,1,24,Ⅱ,인천해역,201903
2,3,3,2019년 1분기,2019,1,3,인천남항 전면,2019. 2. 13. 오후 6:11,0.5,8.12,...,1.63,1,2,3,1,1,28,Ⅱ,인천해역,201903
3,4,4,2019년 1분기,2019,1,4,오이도 북방,2019. 2. 13. 오전 1:57,1.8,8.08,...,1.63,5,5,1,1,1,36,Ⅲ,인천해역,201903
4,5,5,2019년 1분기,2019,1,5,세어도 우측,2019. 2. 13. 오후 7:26,0.9,8.05,...,1.5,4,4,1,1,1,32,Ⅱ,인천해역,201903
5,6,6,2019년 1분기,2019,1,6,영종도 동남방,2019. 2. 13. 오후 5:55,0.7,8.07,...,1.39,1,3,1,1,1,24,Ⅱ,인천해역,201903
6,7,7,2019년 1분기,2019,1,7,무의도 남방,2019. 2. 13. 오전 12:39,2.3,8.05,...,1.14,1,3,1,1,1,24,Ⅱ,인천해역,201903
7,8,8,2019년 1분기,2019,1,8,큰가리섬 서북방향,2019. 2. 13. 오전 1:30,1.7,8.09,...,1.43,1,2,1,1,1,22,Ⅰ,인천해역,201903
8,9,9,2019년 1분기,2019,1,9,대부도 북단,2019. 2. 13. 오전 1:17,1.9,8.07,...,1.46,1,2,4,1,1,31,Ⅱ,인천해역,201903

# 재사용 코드 함수화

In [12]:

def data_load(find_all_tabel):
    dataframe_columns = []
    row = []
    for i, one_data in enumerate(find_all_tabel):
        row.append(one_data.text)
        if len(row) % len(dataframe_header) == 0 and i !=0:
            dataframe_columns.append(row)
            row = []
    return dataframe_columns

# 모든 페이지 조회

In [13]:
buttons = driver.find_elements_by_css_selector('.pagination > li > a')

print([btn.text for btn in buttons])
# 다음과 같은 코드는 한문장으로 작성하는것이 더욱 효율적이다 
# list1 = []
# for btn in buttons :
#     list1.append(btn.text)
# print(list1)

['«', '‹', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '›', '»']

In [14]:
for btn in buttons:
    if btn.text == '›':
        print('존재합니다.')

존재합니다.

# 페이지 조회하여 데이터 크롤링

In [20]:
data_frame_columns_list = []
q = 0
while True:
    q +=1
    if q > 3 : break   
    
    find_all_tabel = driver.find_elements_by_css_selector('tbody > tr > td')    
    nomalized_data = data_load(find_all_tabel)
    
    data_frame_columns_list = data_frame_columns_list + nomalized_data
    
    buttons = driver.find_elements_by_css_selector('.pagination > li > a ')
    
    if '›' in [btn.text for btn in buttons] and 'disabled' not in [btn.get_attribute('class') for btn in buttons]:
        [btn.click() for btn in buttons if btn.text == '›']
        time.sleep(0.5)
    else:
        break

# CSV 파일 저장

In [21]:
dataframe = pd.DataFrame(data_frame_columns_list, columns=dataframe_header)
dataframe

,objectid,OBJECTID,loc_time,loc_year,loc_qtr,loc_no,loc_nm,sample_day,temp,ph,...,toc,din_wqi,dip_wqi,chl_a_wqi,low_do_wqi,transparency_wqi,wqi_score,wqi_grade,gubun,timeseries
0,1,1,2019년 1분기,2019,1,1,인천항 도크앞,2019. 2. 13. 오후 6:24,0.6,8.08,...,1.58,1,3,5,1,1,36,Ⅲ,인천해역,201903
1,2,2,2019년 1분기,2019,1,34,영흥도 서방,2019. 2. 13. 오전 12:30,2,8.02,...,1.24,1,3,1,1,1,24,Ⅱ,인천해역,201903
2,3,3,2019년 1분기,2019,1,3,인천남항 전면,2019. 2. 13. 오후 6:11,0.5,8.12,...,1.63,1,2,3,1,1,28,Ⅱ,인천해역,201903
3,4,4,2019년 1분기,2019,1,4,오이도 북방,2019. 2. 13. 오전 1:57,1.8,8.08,...,1.63,5,5,1,1,1,36,Ⅲ,인천해역,201903
4,5,5,2019년 1분기,2019,1,5,세어도 우측,2019. 2. 13. 오후 7:26,0.9,8.05,...,1.5,4,4,1,1,1,32,Ⅱ,인천해역,201903
5,6,6,2019년 1분기,2019,1,6,영종도 동남방,2019. 2. 13. 오후 5:55,0.7,8.07,...,1.39,1,3,1,1,1,24,Ⅱ,인천해역,201903
6,7,7,2019년 1분기,2019,1,7,무의도 남방,2019. 2. 13. 오전 12:39,2.3,8.05,...,1.14,1,3,1,1,1,24,Ⅱ,인천해역,201903
7,8,8,2019년 1분기,2019,1,8,큰가리섬 서북방향,2019. 2. 13. 오전 1:30,1.7,8.09,...,1.43,1,2,1,1,1,22,Ⅰ,인천해역,201903
8,9,9,2019년 1분기,2019,1,9,대부도 북단,2019. 2. 13. 오전 1:17,1.9,8.07,...,1.46,1,2,4,1,1,31,Ⅱ,인천해역,201903
9,10,10,2019년 1분기,2019,1,10,영흥도 북단,2019. 2. 13. 오전 1:06,1.7,8.07,...,1.13,1,4,1,1,1,26,Ⅱ,인천해역,201903
10,11,11,2019년 1분기,2019,1,11,덕적도 북방(1),2019. 2. 12. 오후 9:31,4.4,7.88,...,1.31,1,4,1,1,3,32,Ⅱ,인천해역,201903
11,12,12,2019년 1분기,2019,1,12,인천공항 하단,2019. 2. 12. 오후 6:57,4.4,7.81,...,1.21,1,4,1,1,1,26,Ⅱ,인천해역,201903
12,13,13,2019년 1분기,2019,1,13,덕적도 북방(2),2019. 2. 12. 오후 9:03,2.7,7.93,...,1.09,1,5,1,1,4,37,Ⅲ,인천해역,201903
13,14,14,2019년 1분기,2019,1,14,용유도 서방,2019. 2. 12. 오후 8:25,2.2,7.87,...,1.2,1,4,1,1,1,26,Ⅱ,인천해역,201903
14,15,15,2019년 1분기,2019,1,15,장봉도 서방,2019. 2. 14. 오후 6:40,1.6,7.99,...,1.46,1,5,1,1,5,40,Ⅲ,강화해역,201903
15,16,16,2019년 1분기,2019,1,16,석모도 서남방,2019. 2. 14. 오후 6:11,0.3,7.93,...,1.84,4,5,1,1,5,46,Ⅲ,강화해역,201903
16,17,17,2019년 1분기,2019,1,17,만석부두 부근,2019. 2. 13. 오후 6:50,0.7,8.06,...,3.26,5,5,1,1,1,36,Ⅲ,인천해역,201903
17,18,18,2019년 1분기,2019,1,18,영흥도 남방,2019. 2. 13. 오전 12:00,2,8.05,...,1.29,1,4,1,1,1,26,Ⅱ,인천해역,201903
18,19,19,2019년 1분기,2019,1,19,선수 앞바다,2019. 2. 14. 오후 5:54,0.8,7.9,...,1.77,5,5,1,1,5,48,Ⅳ,강화해역,201903
19,20,20,2019년 1분기,2019,1,20,교동 아래,2019. 2. 14. 오후 7:26,0.6,7.9,...,2.11,5,5,1,1,5,48,Ⅳ,강화해역,201903
20,21,21,2019년 1분기,2019,1,21,서도 주문도 아래,2019. 2. 14. 오후 6:52,0.8,8.01,...,2.27,2,5,1,1,5,42,Ⅲ,강화해역,201903
21,22,22,2019년 1분기,2019,1,22,창후리 앞바다,2019. 2. 14. 오후 7:36,0.1,7.96,...,2.06,5,5,1,1,5,48,Ⅳ,강화해역,201903
22,23,23,2019년 1분기,2019,1,23,외포리 앞바다,2019. 2. 14. 오후 7:53,0.3,7.95,...,2.08,5,5,1,1,5,48,Ⅳ,강화해역,201903
23,24,24,2019년 1분기,2019,1,24,초지리 앞바다,2019. 2. 13. 오후 7:47,0.6,8.07,...,1.66,5,5,1,1,4,45,Ⅲ,강화해역,201903
24,25,25,2019년 1분기,2019,1,25,운염도 북동방,2019. 2. 13. 오후 7:17,0.7,8.07,...,1.47,5,5,1,1,1,36,Ⅲ,인천해역,201903
25,26,26,2019년 1분기,2019,1,26,LNG기지 북방,2019. 2. 13. 오후 5:41,1.9,7.99,...,1.45,1,3,1,1,1,24,Ⅱ,인천해역,201903
26,27,27,2019년 1분기,2019,1,27,장봉도 서남방,2019. 2. 14. 오후 6:23,0.9,8,...,1.66,2,5,1,1,5,42,Ⅲ,강화해역,201903
27,28,28,2019년 1분기,2019,1,28,덕적도 서방,2019. 2. 12. 오후 10:05,3.6,8,...,1.28,1,5,1,1,5,40,Ⅲ,인천해역,201903
28,29,29,2019년 1분기,2019,1,29,대이작도 동북방,2019. 2. 12. 오후 9:44,3.9,7.97,...,1.09,1,4,1,1,3,32,Ⅱ,인천해역,201903
29,30,30,2019년 1분기,2019,1,30,선갑도 북방,2019. 2. 12. 오후 10:48,2.9,8.02,...,1.12,1,4,1,1,4,35,Ⅲ,인천해역,201903

In [22]:
dataframe.to_csv('created_data.csv', sep=',', header=True, encoding='utf-8-sig')

# https://selenium-python.readthedocs.io/api.html 
# 모든 지원하는 API